cart/dashboard/settings/urls.py
from django.conf.urls import url
from . import views

app_name='settings'
urlpatterns = [
    url(r'^$', views.SettingsView.as_view(), name='index'),
]

cart/dashboard/shipping/urls.py
from django.conf.urls import url
from . import views

app_name='shipping'
urlpatterns = [
    url(r'^$',
        views.BoxListView.as_view(),
        name='box-list'),
    url(r'^create/$',
        views.BoxCreateView.as_view(),
        name='box-create'),
    url(r'^(?P<pk>\d+)$',
        views.BoxUpdateView.as_view(),
        name='box-update'),
    url(r'^delete/(?P<pk>\d+)$',
        views.BoxDeleteView.as_view(),
        name='box-delete'),
]

duxdekes/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
#from django.contrib import admin
from django.contrib.auth import views as auth_views
from oscar.app import application
from oscar.core.loading import get_class
from . import views
#admin.autodiscover()

listing = get_class('catalogue.views', 'CatalogueView')

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^contact/?$', views.Contact.as_view(), name='contact'),
    #url(r'^products/', include('products.urls')),
    #url(r'^admin/', admin.site.urls),
    url(r'^listing/', listing.as_view()),
    url(r'', include(application.urls)),
    url(r'^login/$', auth_views.login, {
        'redirect_field_name': '',
    }, name='login-nextless'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/catalogue/models.py
from oscar.apps.catalogue.abstract_models import \
        AbstractProductClass, AbstractProduct
from oscar.core.loading import get_model
from django.db import models
from .util import product_class, products


class ProductClass(AbstractProductClass):
    """
    Override the product class save method to add required attributes
    """

    def save(self, *args, **kwargs):
        """
        Save the object as usual, and then call the utility function to add
        required attributes to all product classes
        """
        super().save()

        # Make sure ALL product classes have the right attributes
        product_class.make_class_attributes()


class Product(AbstractProduct):
    """
    Add an "active" flag to the product class
    """
    is_active = models.BooleanField(default=True)


# Import the remaining Oscar models
from oscar.apps.catalogue.models import *  # noqa
StockRecord = get_model('partner', 'StockRecord')


class InstructionsProduct(Product):
    """
    A product specifically designed to be used for special instructions
    """
    TITLE_ALONE = '{} Painting Kit'
    TITLE_WITH_BLANK = '{} Painting Kit & {} blank'
    SKU_WITH_BLANK_UPC = '{}B'

    sku = models.CharField(max_length=64)
    price = models.DecimalField(max_digits=12,
            decimal_places=2)
    price_with_blank = models.DecimalField(max_digits=12,
            decimal_places=2,
            blank=True,
            null=True)
    blank = models.ForeignKey(Product,
            related_name='paired_blank',
            blank=True,
            null=True)
    alone_stock = models.ForeignKey(StockRecord,
            related_name='alone',
            blank=True,
            null=True)
    with_blank_stock = models.ForeignKey(StockRecord,
            related_name='with_blank',
            blank=True,
            null=True)

    def save(self, *args, **kwargs):
        """
        Save the model, and hook up a bunch of other Oscar-specific connections
        """
        self.product_class = products.get_instructions_class()
        self.structure = Product.PARENT

        # Save this model the ol' fashioned way
        super().save(*args, **kwargs)

        # Stock records and child products for a la carte instructions
        new_alone = not self.alone_stock
        if new_alone:
            alone = Product()
            alone.parent = self
            alone.structure = Product.CHILD

            alone_stock = StockRecord()
            alone_stock.partner = products.get_partner()
        else:
            alone_stock = self.alone_stock
            alone = self.alone_stock.product
        
        alone.title = self.TITLE_ALONE.format(self.title)
        #alone.upc = self.sku
        alone.save()

        if new_alone:
            alone_stock.product = alone

        alone_stock.partner_sku = self.sku
        alone_stock.price_excl_tax = self.price
        alone_stock.save()

        self.alone_stock = alone_stock

        # Stock records and child products for instructions with blank
        if self.blank and self.price_with_blank:
            new_w_blank = not self.with_blank_stock
            if new_w_blank:
                with_blank = Product()
                with_blank.parent = self
                with_blank.structure = Product.CHILD

                with_blank_stock = StockRecord()
                with_blank_stock.partner = products.get_partner()
            else:
                with_blank_stock = self.with_blank_stock
                with_blank = with_blank_stock.product
            
            with_blank.title = self.TITLE_WITH_BLANK.format(self.title,
                    self.blank.title)
            #with_blank.upc = self.SKU_WITH_BLANK.format(self.sku)
            with_blank.save()

            if new_w_blank:
                with_blank_stock.product = with_blank

            with_blank_stock.partner_sku = \
                self.SKU_WITH_BLANK_UPC.format(self.sku)
            with_blank_stock.price_excl_tax = self.price_with_blank
            with_blank_stock.save()

            self.with_blank_stock = with_blank_stock
        else:
            new_w_blank = False

        # If either of these have been added, we need to re-save the model to
        # point to the new StockRecord objects
        if new_alone or new_w_blank:
            super().save(*args, **kwargs)



#class BookInstructionsProduct(Product):
#    """
#    Override the usual product model to include extra descriptive content
#    """
#    extra_content = models.ForeignKey(FlatPage,
#            blank = True,
#            null = True)

cart/dashboard/models.py
from oscar.apps.dashboard.models import *  # noqa

cart/dashboard/orders/forms.py
from django import forms
from oscar.core.loading import get_class, get_model


class DiscountOrderForm(forms.Form):
    """
    A form used to accept a new basket total
    """
    final_basket_total = forms.DecimalField(label="Final basket total")

class FinalizeOrderForm(forms.Form):
    """
    A form specifically tailored to creating Instructions product
    """
    final_shipping = forms.DecimalField(label="Actual Shipping Cost")

cart/dashboard/catalogue/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views import generic
from django.utils.translation import ugettext_lazy as _
from django_tables2 import SingleTableView
from oscar.core.loading import get_class, get_classes, get_model
from . import forms, tables
from duxdekes.util import products


# Dynamically get any oscar models/classes in use
InstructionsProduct = get_model('catalogue', 'InstructionsProduct')
ProductTable, CategoryTable \
    = get_classes('dashboard.catalogue.tables',
                  ('ProductTable', 'CategoryTable'))
ProductCategoryFormSet, ProductImageFormSet, ProductAttributesFormSet \
    = get_classes('dashboard.catalogue.forms',
        (
            'ProductCategoryFormSet',
            'ProductImageFormSet',
            'ProductAttributesFormSet',
        ))
ProductDeleteView = get_class('dashboard.catalogue.views', 'ProductDeleteView')
Product = get_model('catalogue', 'Product')
ProductClass = get_model('catalogue', 'ProductClass')
StockRecord = get_model('partner', 'StockRecord')


class ProductMixin:
    """
    A basic mixin used for all of our custom products
    """
    cached_product_class = False
    category_formset = ProductCategoryFormSet
    image_formset = ProductImageFormSet

    def __init__(self, *args, **kwargs):
        """
        Override to set up the formsets dictionary
        """
        super().__init__(*args, **kwargs)

        self.formsets = {
            'category_formset': self.category_formset,
            'image_formset': self.image_formset,
        }
        self.queryset = Product.objects.filter(product_class=self.get_product_class())

    def get_context_data(self, *args, **kwargs):
        """
        Override get_context_data to fix the page title
        """
        context = super().get_context_data(*args, **kwargs)

        # Set the product title, if set
        if self.view_title:
            context['title'] = self.view_title

        # Add the product formsets
        instance = None
        if self.object:
            instance = self.object

        for ctx_name, formset_class in self.formsets.items():
            if ctx_name not in context:
                context[ctx_name] = formset_class(self.product_class,
                                                  self.request.user,
                                                  instance=instance)

        if not 'product_class' in context:
            context['product_class'] = self.product_class

        return context

    def post(self, request, *args, **kwargs):
        """
        Override post method to save formsets
        """

        initial_response = super().post(request, *args, **kwargs)

        # check for failure of initial form
        if not isinstance(initial_response, HttpResponseRedirect):
            return initial_response

        # Process formsets
        formsets = {}

        for key, formset in self.formsets.items():
            formsets[key] = formset(self.product_class,
                                    request.user,
                                    request.POST,
                                    request.FILES,
                                    instance=self.object)

        if all([formset.is_valid() for formset in formsets.values()]):
            for formset in formsets.values():
                formset.save()

            # All is well - return success!
            messages.success(request,
                             getattr(self, 'success_message',
                                     'Product successfully saved.'),
                             extra_tags="safe noicon")
            return initial_response

        else:
            return self.form_invalid(self.get_form())

    @property
    def product_class(self):
        """
        Must be implemented on each extending mixin!
        """
        if not self.cached_product_class:
            try:
                self.cached_product_class = self.get_product_class()
            except:
                raise NotImplemented('No product class defined!')

        return self.cached_product_class


class FinishedListView(SingleTableView):
    """
    Display a list of Finished Decoys
    """
    template_name = 'dashboard/catalogue/product_finished.html'
    table_class = tables.FinishedTable
    context_table_name = 'products'
    queryset = Product.objects.filter(product_class=products.get_finished_class())

    def get_table(self, **kwargs):
        """
        Set the table caption by overriding the parent method
        """
        table = super().get_table(**kwargs)
        table.caption = 'Finished Decoys'
        return table


class FinishedMixin(ProductMixin):
    """
    Contain common functionality for create and update views
    """
    form_class = forms.FinishedForm
    success_url = reverse_lazy('dashboard:catalogue-finished-list')
    success_message = 'Decoy successfully saved'
    template_name = 'dashboard/catalogue/product_finished_update.html'

    def get_product_class(self):
        """
        Return the product class associated with this type of product
        """
        return products.get_finished_class()


class FinishedCreateView(FinishedMixin, generic.CreateView):
    """
    Create an finished decoy
    """
    view_title = 'Add Finished Decoy'


class FinishedUpdateView(FinishedMixin, generic.UpdateView):
    """
    Update an finished decoy
    """
    view_title = 'Change Finished Decoy'

    def get_initial(self):
        """
        If there has been a product sent in, get its values and pre-populate
        the form
        """
        initial = super().get_initial()

        # Set the price from the related stock record
        try:
            stock = StockRecord.objects.get(product=self.object)
            initial['price'] = stock.price_excl_tax
        except:
            pass

        # Get the pricing/sku details
        return initial

    def get_object(self):
        """
        Populate the existing object if one has been sent in
        """
        if 'pk' in self.kwargs:
            return Product.objects.get(pk=self.kwargs.get('pk'))

        return None


class FinishedDeleteView(ProductDeleteView):
    """
    Override the get_success_url method of the generic ProductDeleteView to send us
    back to the finished decoy section
    """
    view_title = 'Remove Finished Decoy'

    def get_success_url(self):
        """
        When deleting child products, this view redirects to editing the
        parent product. When deleting any other product, it redirects to the
        product list view.
        """
        if self.object.is_child:
            msg = _("Deleted product variant '%s'") % self.object.get_title()
            messages.success(self.request, msg)
            return reverse(
                'dashboard:catalogue-finished',
                kwargs={'pk': self.object.parent_id})
        else:
            msg = _("Deleted product '%s'") % self.object.title
            messages.success(self.request, msg)
            return reverse('dashboard:catalogue-finished-list')


class InstructionsListView(SingleTableView):
    template_name = 'dashboard/catalogue/product_instructions.html'
    table_class = tables.InstructionsTable
    context_table_name = 'products'
    model = InstructionsProduct

    def get_table(self, **kwargs):
        """
        Set the table caption by overriding the parent method
        """
        table = super().get_table(**kwargs)
        table.caption = 'Instructions'
        return table


class InstructionsMixin(ProductMixin):
    """
    Contain common functionality for create and update views
    """
    form_class = forms.InstructionsForm
    model = InstructionsProduct
    success_url = reverse_lazy('dashboard:catalogue-instructions-list')
    success_message = 'Instructions successfully saved'
    template_name = 'dashboard/catalogue/product_instructions_update.html'

    def __init__(self, *args, **kwargs):
        """
        We don't need no stinkin' queryset
        """
        super().__init__(*args, **kwargs)
        del self.queryset

    def get_product_class(self):
        """
        Return the product class associated with this type of product
        """
        return products.get_instructions_class()


class InstructionsCreateView(InstructionsMixin, generic.CreateView):
    """
    Create an instruction
    """
    view_title = 'Add Instructions'


class InstructionsUpdateView(InstructionsMixin, generic.UpdateView):
    """
    Update an instruction product
    """
    view_title = 'Change Instructions'


class InstructionsDeleteView(ProductDeleteView):
    """
    Override the get_success_url method of the generic ProductDeleteView to send us
    back to the instruction section
    """
    def get_success_url(self):
        """
        When deleting child products, this view redirects to editing the
        parent product. When deleting any other product, it redirects to the
        product list view.
        """
        if self.object.is_child:
            msg = _("Deleted product variant '%s'") % self.object.get_title()
            messages.success(self.request, msg)
            return reverse(
                'dashboard:catalogue-instructions',
                kwargs={'pk': self.object.parent_id})
        else:
            msg = _("Deleted product '%s'") % self.object.title
            messages.success(self.request, msg)
            return reverse('dashboard:catalogue-instructions-list')



class UnfinishedListView(SingleTableView):
    """
    Dashboard view that lists existing finished decoys
    """
    context_table_name = 'products'
    queryset = Product.objects.filter(product_class=products.get_unfinished_class())
    table_class = tables.UnfinishedTable
    template_name = 'dashboard/catalogue/product_unfinished.html'

    def get_table(self, **kwargs):
        """

cart/dashboard/shipping/views.py
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django_tables2 import SingleTableView
from oscar.core.loading import get_class, get_classes, get_model
from . import tables

Box = get_model('shipping', 'Box')

BOX_TEMPLATE_DIR = 'dashboard/shipping'


class BoxListView(SingleTableView):
    template_name = '{}/list.html'.format(BOX_TEMPLATE_DIR)
    table_class = tables.BoxTable
    context_table_name = 'boxes'
    model = Box

    def get_table(self, **kwargs):
        """
        Set the table caption by overriding the parent method
        """
        table = super().get_table(**kwargs)
        table.caption = 'Box Sizes'
        return table

class BoxMixin():
    fields = ['length', 'width', 'height']
    model = Box
    success_url = reverse_lazy('dashboard:shipping:box-list')

class BoxCreateView(BoxMixin, generic.CreateView):
    template_name = '{}/update.html'.format(BOX_TEMPLATE_DIR)


class BoxUpdateView(BoxMixin, generic.UpdateView):
    template_name = '{}/update.html'.format(BOX_TEMPLATE_DIR)


class BoxDeleteView(BoxMixin, generic.DeleteView):
    template_name = '{}/delete.html'.format(BOX_TEMPLATE_DIR)

templates/dashboard/catalogue/finished_row_actions.html
{% load django_tables2 %}
{% load i18n %}
<div class="btn-toolbar">
    <div class="btn-group">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
            {% trans "Actions" %}
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="{% url 'dashboard:catalogue-finished' pk=record.id %}{% querystring %}">{% trans "Edit" %}</a>
            </li>
            <li>
                <a href="{{ record.get_absolute_url }}"> {% trans "View on site" %}</a>
            </li>
            <li>
                <a href="{% url 'dashboard:catalogue-finished-delete' pk=record.id %}">{% trans "Delete" %}</a>
            </li>
        </ul>
    </div>
</div>

templates/dashboard/catalogue/finished_row_title.html
{% load django_tables2 %}
<a href="{% url 'dashboard:catalogue-finished' pk=record.pk %}{% querystring %}">{{ value }}</a>

templates/dashboard/catalogue/instructions_row_actions.html
{% load django_tables2 %}
{% load i18n %}
<div class="btn-toolbar">
    <div class="btn-group">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
            {% trans "Actions" %}
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="{% url 'dashboard:catalogue-instructions' pk=record.id %}{% querystring %}">{% trans "Edit" %}</a>
            </li>
            <li>
                <a href="{{ record.get_absolute_url }}"> {% trans "View on site" %}</a>
            </li>
            <li>
                <a href="{% url 'dashboard:catalogue-instructions-delete' pk=record.id %}">{% trans "Delete" %}</a>
            </li>
        </ul>
    </div>
</div>

templates/dashboard/catalogue/instructions_row_title.html
{% load django_tables2 %}
<a href="{% url 'dashboard:catalogue-instructions' pk=record.pk %}{% querystring %}">{{ value }}</a>

templates/dashboard/catalogue/product_finished.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}
{% load thumbnail %}
{% load staticfiles %}
{% load sorting_tags %}
{% load render_table from django_tables2 %}

{% block body_class %}{{ block.super }} catalogue{% endblock %}

{% block title %}
    Finished Decoys | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li class="active">Finished Decoys</li>
    </ul>
{% endblock %}

{% block header %}
    <div class="page-header action">
        <h1>Finished Decoys</h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    {% block create_product %}
        <div class="table-header">
            <h3><i class="icon-sitemap icon-large"></i> {% trans "Create new product" %}</h3>
        </div>
        <div class="well">
            <form action="{% url 'dashboard:catalogue-finished-create' %}" method="get" class="form-inline">
                <button class="btn btn-primary" type="submit" data-loading-text="{% trans 'Submitting...' %}"><i class="icon-plus"></i> {% trans "New Product" %}</button>
            </form>
        </div>
    {% endblock %}

    {% block search_products %}
    {% endblock %}

    {% if products %}
        {% block product_list %}
            <form action="." method="post">
                {% csrf_token %}
                {% render_table products %}
            </form>
        {% endblock product_list %}
    {% else %}
        <p>{% trans "No products found." %}</p>
    {% endif %}

{% endblock dashboard_content %}

templates/dashboard/catalogue/product_instructions.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}
{% load thumbnail %}
{% load staticfiles %}
{% load sorting_tags %}
{% load render_table from django_tables2 %}

{% block body_class %}{{ block.super }} catalogue{% endblock %}

{% block title %}
    Instructions | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li class="active">Instructions</li>
    </ul>
{% endblock %}

{% block header %}
    <div class="page-header action">
        <h1>Instructions</h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    {% block create_product %}
        <div class="table-header">
            <h3><i class="icon-sitemap icon-large"></i> Create new Instructions</h3>
        </div>
        <div class="well">
            <form action="{% url 'dashboard:catalogue-instructions-create' %}" method="get" class="form-inline">
                <button class="btn btn-primary" type="submit"
					data-loading-text="{% trans 'Submitting...' %}"><i
						class="icon-plus"></i> {% trans "New Instructions" %}</button>
            </form>
        </div>
    {% endblock %}

    {% block search_products %}
    {% endblock %}

    {% if products %}
        {% block product_list %}
            <form action="." method="post">
                {% csrf_token %}
                {% render_table products %}
            </form>
        {% endblock product_list %}
    {% else %}
        <p>{% trans "No products found." %}</p>
    {% endif %}

{% endblock dashboard_content %}

templates/dashboard/catalogue/product_unfinished.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}
{% load thumbnail %}
{% load staticfiles %}
{% load sorting_tags %}
{% load render_table from django_tables2 %}

{% block body_class %}{{ block.super }} catalogue{% endblock %}

{% block title %}
    Unfinished Blanks | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li class="active">Unfinished Blanks</li>
    </ul>
{% endblock %}

{% block header %}
    <div class="page-header action">
        <h1>Unfinished Blanks</h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    {% block create_product %}
        <div class="table-header">
            <h3><i class="icon-sitemap icon-large"></i> {% trans "Create new product" %}</h3>
        </div>
        <div class="well">
            <form action="{% url 'dashboard:catalogue-unfinished-create' %}" method="get" class="form-inline">
                <button class="btn btn-primary" type="submit" data-loading-text="{% trans 'Submitting...' %}"><i class="icon-plus"></i> {% trans "New Product" %}</button>
            </form>
        </div>
    {% endblock %}

    {% block search_products %}
    {% endblock %}

    {% if products %}
        {% block product_list %}
            <form action="." method="post">
                {% csrf_token %}
                {% render_table products %}
            </form>
        {% endblock product_list %}
    {% else %}
        <p>{% trans "No products found." %}</p>
    {% endif %}

{% endblock dashboard_content %}

templates/dashboard/catalogue/unfinished_row_actions.html
{% load django_tables2 %}
{% load i18n %}
<div class="btn-toolbar">
    <div class="btn-group">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
            {% trans "Actions" %}
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="{% url 'dashboard:catalogue-unfinished' pk=record.id %}{% querystring %}">{% trans "Edit" %}</a>
            </li>
            <li>
                <a href="{{ record.get_absolute_url }}"> {% trans "View on site" %}</a>
            </li>
            <li>
                <a href="{% url 'dashboard:catalogue-unfinished-delete' pk=record.id %}">{% trans "Delete" %}</a>
            </li>
        </ul>
    </div>
</div>

templates/dashboard/catalogue/unfinished_row_title.html
{% load django_tables2 %}
<a href="{% url 'dashboard:catalogue-unfinished' pk=record.pk %}{% querystring %}">{{ value }}</a>